services:
  nosql.db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  websitecollections.playground:
    image: ${DOCKER_REGISTRY-}websitecollectionsplayground
    build:
      context: .
      dockerfile: WebsiteCollections.Playground/Dockerfile
    ports:
      - "8080:8080"

volumes:
  mongodb_data: