@WebsiteCollections.Playground_HostAddress = http://localhost:8080

### Get all collections
GET {{WebsiteCollections.Playground_HostAddress}}/collections/
Accept: application/json

### Get "development" collection
GET {{WebsiteCollections.Playground_HostAddress}}/collections/development
Accept: application/json

### Add new website to collection
POST {{WebsiteCollections.Playground_HostAddress}}/collections/
Accept: application/json
Content-Type: application/json
{
  "url": "https://github.com/ardalis/ApiEndpoints",
  "collection": "development",
  "title": "Ardalis ApiEndpoints"
}

### Health check
GET {{WebsiteCollections.Playground_HostAddress}}/health
Accept: application/json
